{{- if .Values.kroki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-kroki.krokiServiceName" . }}
  labels:
    {{- include "mcp-kroki.labels" . | nindent 4 }}
    app.kubernetes.io/component: kroki
spec:
  type: {{ .Values.kroki.service.type }}
  ports:
    - port: {{ .Values.kroki.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-kroki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kroki
{{- end }}
